/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.3-0-gc1071ab+c1071ab3197f9bbf718123ec5bbabf449b2f7bab

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   OD.h; OD.c
        Project File: LM_Slaver.xdd
        File Version: 1

        Created:      2025/10/8 14:51:11
        Created By:   zjcszn
        Modified:     2025/10/11 17:03:57
        Modified By:  zjcszn

    Device Info:
        Vendor Name:  AUTOOL
        Vendor ID:    0x00ECA527
        Product Name: LM Slaver
        Product ID:   0x00000002

        Description:  LM Slaver
*******************************************************************************/

#ifndef OD_H
#define OD_H
/*******************************************************************************
    Counters of OD objects
*******************************************************************************/
#define OD_CNT_NMT 1
#define OD_CNT_EM 1
#define OD_CNT_SYNC 1
#define OD_CNT_SYNC_PROD 1
#define OD_CNT_STORAGE 1
#define OD_CNT_EM_PROD 1
#define OD_CNT_HB_CONS 1
#define OD_CNT_HB_PROD 1
#define OD_CNT_SDO_CLI 1
#define OD_CNT_RPDO 4
#define OD_CNT_TPDO 4


/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/
#define OD_CNT_ARR_1003 16
#define OD_CNT_ARR_1010 4
#define OD_CNT_ARR_1011 4
#define OD_CNT_ARR_1016 8


/*******************************************************************************
    OD data declaration of all groups
*******************************************************************************/
typedef struct {
    uint32_t x1000_deviceType;
    uint32_t x1005_COB_ID_SYNCMessage;
    uint32_t x1006_communicationCyclePeriod;
    uint32_t x1007_synchronousWindowLength;
    uint32_t x1014_COB_ID_EMCY;
    uint16_t x1015_inhibitTimeEMCY;
    uint8_t x1016_consumerHeartbeatTime_sub0;
    uint32_t x1016_consumerHeartbeatTime[OD_CNT_ARR_1016];
    uint16_t x1017_producerHeartbeatTime;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t vendor_ID;
        uint32_t productCode;
        uint32_t revisionNumber;
        uint32_t serialNumber;
    } x1018_identity;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDClientToServerTx;
        uint32_t COB_IDServerToClientRx;
        uint8_t node_IDOfTheSDOServer;
    } x1280_SDOClientParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1400_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1401_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1402_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1403_RPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1600_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1601_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1602_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1603_RPDOMappingParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1800_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1801_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1802_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1803_TPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1A00_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1A01_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1A02_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1A03_TPDOMappingParameter;
} OD_PERSIST_COMM_t;

typedef struct {
    uint8_t x1001_errorRegister;
    uint8_t x1010_storeParameters_sub0;
    uint32_t x1010_storeParameters[OD_CNT_ARR_1010];
    uint8_t x1011_restoreDefaultParameters_sub0;
    uint32_t x1011_restoreDefaultParameters[OD_CNT_ARR_1011];
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t sw_ver;
    } x2000_board;
    struct {
        uint8_t highestSub_indexSupported;
        int16_t tank;
        int16_t PAG;
        int16_t POE;
        int16_t waste_oil;
    } x2001_loadCell;
    struct {
        uint8_t highestSub_indexSupported;
        int32_t tank;
        int32_t PAG;
        int32_t POE;
        int32_t waste_oil;
    } x2002_loadCell_RAW;
    struct {
        uint8_t highestSub_indexSupported;
        int16_t tank;
        int16_t line;
        int16_t block;
    } x2003_pressure;
    struct {
        uint8_t highestSub_indexSupported;
        float32_t tank_coeff;
        float32_t tank_zero;
        float32_t PAG_coeff;
        float32_t PAG_zero;
        float32_t POE_coeff;
        float32_t POE_zero;
        float32_t waste_oil_coeff;
        float32_t waste_oil_zero;
    } x2004_loadCell_Params;
    struct {
        uint8_t highestSub_indexSupported;
        float32_t tank_zero;
        float32_t line_zero;
        float32_t block_zero;
    } x2005_pressure_Params;
    uint32_t x2006_DO_Set;
    uint32_t x2007_DO_Reset;
    uint32_t x2008_DO_Status;
    uint16_t x2009_DI_Status;
    uint16_t x200A_command;
    uint32_t x200B_cmd_Params;
    struct {
        uint8_t highestSub_indexSupported;
        uint8_t status;
        uint16_t progress;
        uint32_t result;
    } x200C_cmd_Status;
} OD_RAM_t;

#ifndef OD_ATTR_PERSIST_COMM
#define OD_ATTR_PERSIST_COMM
#endif
extern OD_ATTR_PERSIST_COMM OD_PERSIST_COMM_t OD_PERSIST_COMM;

#ifndef OD_ATTR_RAM
#define OD_ATTR_RAM
#endif
extern OD_ATTR_RAM OD_RAM_t OD_RAM;

#ifndef OD_ATTR_OD
#define OD_ATTR_OD
#endif
extern OD_ATTR_OD OD_t *OD;


/*******************************************************************************
    Object dictionary entries - shortcuts
*******************************************************************************/
#define OD_ENTRY_H1000 &OD->list[0]
#define OD_ENTRY_H1001 &OD->list[1]
#define OD_ENTRY_H1003 &OD->list[2]
#define OD_ENTRY_H1005 &OD->list[3]
#define OD_ENTRY_H1006 &OD->list[4]
#define OD_ENTRY_H1007 &OD->list[5]
#define OD_ENTRY_H1010 &OD->list[6]
#define OD_ENTRY_H1011 &OD->list[7]
#define OD_ENTRY_H1014 &OD->list[8]
#define OD_ENTRY_H1015 &OD->list[9]
#define OD_ENTRY_H1016 &OD->list[10]
#define OD_ENTRY_H1017 &OD->list[11]
#define OD_ENTRY_H1018 &OD->list[12]
#define OD_ENTRY_H1280 &OD->list[13]
#define OD_ENTRY_H1400 &OD->list[14]
#define OD_ENTRY_H1401 &OD->list[15]
#define OD_ENTRY_H1402 &OD->list[16]
#define OD_ENTRY_H1403 &OD->list[17]
#define OD_ENTRY_H1600 &OD->list[18]
#define OD_ENTRY_H1601 &OD->list[19]
#define OD_ENTRY_H1602 &OD->list[20]
#define OD_ENTRY_H1603 &OD->list[21]
#define OD_ENTRY_H1800 &OD->list[22]
#define OD_ENTRY_H1801 &OD->list[23]
#define OD_ENTRY_H1802 &OD->list[24]
#define OD_ENTRY_H1803 &OD->list[25]
#define OD_ENTRY_H1A00 &OD->list[26]
#define OD_ENTRY_H1A01 &OD->list[27]
#define OD_ENTRY_H1A02 &OD->list[28]
#define OD_ENTRY_H1A03 &OD->list[29]
#define OD_ENTRY_H2000 &OD->list[30]
#define OD_ENTRY_H2001 &OD->list[31]
#define OD_ENTRY_H2002 &OD->list[32]
#define OD_ENTRY_H2003 &OD->list[33]
#define OD_ENTRY_H2004 &OD->list[34]
#define OD_ENTRY_H2005 &OD->list[35]
#define OD_ENTRY_H2006 &OD->list[36]
#define OD_ENTRY_H2007 &OD->list[37]
#define OD_ENTRY_H2008 &OD->list[38]
#define OD_ENTRY_H2009 &OD->list[39]
#define OD_ENTRY_H200A &OD->list[40]
#define OD_ENTRY_H200B &OD->list[41]
#define OD_ENTRY_H200C &OD->list[42]


/*******************************************************************************
    Object dictionary entries - shortcuts with names
*******************************************************************************/
#define OD_ENTRY_H1000_deviceType &OD->list[0]
#define OD_ENTRY_H1001_errorRegister &OD->list[1]
#define OD_ENTRY_H1003_pre_definedErrorField &OD->list[2]
#define OD_ENTRY_H1005_COB_ID_SYNCMessage &OD->list[3]
#define OD_ENTRY_H1006_communicationCyclePeriod &OD->list[4]
#define OD_ENTRY_H1007_synchronousWindowLength &OD->list[5]
#define OD_ENTRY_H1010_storeParameters &OD->list[6]
#define OD_ENTRY_H1011_restoreDefaultParameters &OD->list[7]
#define OD_ENTRY_H1014_COB_ID_EMCY &OD->list[8]
#define OD_ENTRY_H1015_inhibitTimeEMCY &OD->list[9]
#define OD_ENTRY_H1016_consumerHeartbeatTime &OD->list[10]
#define OD_ENTRY_H1017_producerHeartbeatTime &OD->list[11]
#define OD_ENTRY_H1018_identity &OD->list[12]
#define OD_ENTRY_H1280_SDOClientParameter &OD->list[13]
#define OD_ENTRY_H1400_RPDOCommunicationParameter &OD->list[14]
#define OD_ENTRY_H1401_RPDOCommunicationParameter &OD->list[15]
#define OD_ENTRY_H1402_RPDOCommunicationParameter &OD->list[16]
#define OD_ENTRY_H1403_RPDOCommunicationParameter &OD->list[17]
#define OD_ENTRY_H1600_RPDOMappingParameter &OD->list[18]
#define OD_ENTRY_H1601_RPDOMappingParameter &OD->list[19]
#define OD_ENTRY_H1602_RPDOMappingParameter &OD->list[20]
#define OD_ENTRY_H1603_RPDOMappingParameter &OD->list[21]
#define OD_ENTRY_H1800_TPDOCommunicationParameter &OD->list[22]
#define OD_ENTRY_H1801_TPDOCommunicationParameter &OD->list[23]
#define OD_ENTRY_H1802_TPDOCommunicationParameter &OD->list[24]
#define OD_ENTRY_H1803_TPDOCommunicationParameter &OD->list[25]
#define OD_ENTRY_H1A00_TPDOMappingParameter &OD->list[26]
#define OD_ENTRY_H1A01_TPDOMappingParameter &OD->list[27]
#define OD_ENTRY_H1A02_TPDOMappingParameter &OD->list[28]
#define OD_ENTRY_H1A03_TPDOMappingParameter &OD->list[29]
#define OD_ENTRY_H2000_board &OD->list[30]
#define OD_ENTRY_H2001_loadCell &OD->list[31]
#define OD_ENTRY_H2002_loadCell_RAW &OD->list[32]
#define OD_ENTRY_H2003_pressure &OD->list[33]
#define OD_ENTRY_H2004_loadCell_Params &OD->list[34]
#define OD_ENTRY_H2005_pressure_Params &OD->list[35]
#define OD_ENTRY_H2006_DO_Set &OD->list[36]
#define OD_ENTRY_H2007_DO_Reset &OD->list[37]
#define OD_ENTRY_H2008_DO_Status &OD->list[38]
#define OD_ENTRY_H2009_DI_Status &OD->list[39]
#define OD_ENTRY_H200A_command &OD->list[40]
#define OD_ENTRY_H200B_cmd_Params &OD->list[41]
#define OD_ENTRY_H200C_cmd_Status &OD->list[42]


/*******************************************************************************
    OD config structure
*******************************************************************************/
#ifdef CO_MULTIPLE_OD
#define OD_INIT_CONFIG(config) {\
    (config).CNT_NMT = OD_CNT_NMT;\
    (config).ENTRY_H1017 = OD_ENTRY_H1017;\
    (config).CNT_HB_CONS = OD_CNT_HB_CONS;\
    (config).CNT_ARR_1016 = OD_CNT_ARR_1016;\
    (config).ENTRY_H1016 = OD_ENTRY_H1016;\
    (config).CNT_EM = OD_CNT_EM;\
    (config).ENTRY_H1001 = OD_ENTRY_H1001;\
    (config).ENTRY_H1014 = OD_ENTRY_H1014;\
    (config).ENTRY_H1015 = OD_ENTRY_H1015;\
    (config).CNT_ARR_1003 = OD_CNT_ARR_1003;\
    (config).ENTRY_H1003 = OD_ENTRY_H1003;\
    (config).CNT_SDO_SRV = 0;\
    (config).ENTRY_H1200 = NULL;\
    (config).CNT_SDO_CLI = OD_CNT_SDO_CLI;\
    (config).ENTRY_H1280 = OD_ENTRY_H1280;\
    (config).CNT_TIME = 0;\
    (config).ENTRY_H1012 = NULL;\
    (config).CNT_SYNC = OD_CNT_SYNC;\
    (config).ENTRY_H1005 = OD_ENTRY_H1005;\
    (config).ENTRY_H1006 = OD_ENTRY_H1006;\
    (config).ENTRY_H1007 = OD_ENTRY_H1007;\
    (config).ENTRY_H1019 = NULL;\
    (config).CNT_RPDO = OD_CNT_RPDO;\
    (config).ENTRY_H1400 = OD_ENTRY_H1400;\
    (config).ENTRY_H1600 = OD_ENTRY_H1600;\
    (config).CNT_TPDO = OD_CNT_TPDO;\
    (config).ENTRY_H1800 = OD_ENTRY_H1800;\
    (config).ENTRY_H1A00 = OD_ENTRY_H1A00;\
    (config).CNT_LEDS = 0;\
    (config).CNT_GFC = 0;\
    (config).ENTRY_H1300 = NULL;\
    (config).CNT_SRDO = 0;\
    (config).ENTRY_H1301 = NULL;\
    (config).ENTRY_H1381 = NULL;\
    (config).ENTRY_H13FE = NULL;\
    (config).ENTRY_H13FF = NULL;\
    (config).CNT_LSS_SLV = 0;\
    (config).CNT_LSS_MST = 0;\
    (config).CNT_GTWA = 0;\
    (config).CNT_TRACE = 0;\
}
#endif

#endif /* OD_H */
